apiVersion: v2
appVersion: "1.9"
description: Teedy is an open source, lightweight document management system for individuals and businesses.
name: teedy
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
- teedy
- documents
- management
home: https://github.com/truecharts/apps/tree/master/charts/stable/teedy
icon: https://raw.githubusercontent.com/sismics/docs/v1.9/docs-web/src/main/resources/image/logo.png
sources:
- https://github.com/sismics/docs
- https://github.com/truecharts/apps/tree/master/charts/teedy
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.3.9
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 3.0.16
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
