##
# This file contains Values.yaml content that gets added to the output of questions.yaml
# It's ONLY meant for content that the user is NOT expected to change.
# Example: Everything under "image" is not included in questions.yaml but is included here.
##

image:
  repository: openkm/openkm-ce
  pullPolicy: IfNotPresent
  tag: 6.3.11@sha256:15bf6110539b02795a52f4472d95511736cfbdedef8396baf24c65a3aae28814

initContainers:
  init:
    image: "{{ .Values.alpineImage.repository }}:{{ .Values.alpineImage.tag }}"
    command: ["/config/init/init.sh"]
    volumeMounts:
      - name: init
        mountPath: /config/init
      - name: config
        mountPath: /opt/tomcat

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: openkm
  postgresqlDatabase: openkm
  persistence:
    db:
      storageClass: "SCALE-ZFS"
    dbbackups:
      storageClass: "SCALE-ZFS"

##
# Most other defaults are set in questions.yaml
# For other options please refer to the wiki, default_values.yaml or the common library chart
##
