##
# This file contains Values.yaml content that gets added to the output of questions.yaml
# It's ONLY meant for content that the user is NOT expected to change.
# Example: Everything under "image" is not included in questions.yaml but is included here.
##

image:
  repository: gotify/server
  pullPolicy: IfNotPresent
  tag: 2.1.0@sha256:57aa2aabac035c16118f625dd6d3d2c3ca421b43b28cb27512f3212193d65771

envFrom:
  - configMapRef:
      name: gotifyenv

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: gotify
  postgresqlDatabase: gotify
  persistence:
    db:
      storageClass: "SCALE-ZFS"
    dbbackups:
      storageClass: "SCALE-ZFS"

##
# Most other defaults are set in questions.yaml
# For other options please refer to the wiki, default_values.yaml or the common library chart
##
