image:
  repository: ghcr.io/crazy-max/firefox-syncserver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.8.0@sha256:15aeaaec65295711260807fe49020b2e446e60d6e094d60a1cfd96c7ebf2b9ce

secret:
  FF_SYNCSERVER_SECRET: "5up3rS3kr1t"

securityContext:
  runAsNonRoot: false
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TZ: "America/Los_Angeles"
  FF_SYNCSERVER_PUBLIC_URL: "firefox-syncserver.192.168.1.189.nip.io"
  FF_SYNCSERVER_FORCE_WSGI_ENVIRON: "true"
  PUID: "568"
  # FF_SYNCSERVER_ACCESSLOG: "false"
  # FF_SYNCSERVER_LOGLEVEL: info
  # FF_SYNCSERVER_ALLOW_NEW_USERS: "true"
  # FF_SYNCSERVER_FORWARDED_ALLOW_IPS: *

envValueFrom:
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: url

service:
  main:
    ports:
      main:
        port: 5000

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: firefox-syncserver
  postgresqlDatabase: firefox-syncserver
