##
# This file contains Values.yaml content that gets added to the output of questions.yaml
# It's ONLY meant for content that the user is NOT expected to change.
# Example: Everything under "image" is not included in questions.yaml but is included here.
##

image:
  repository: ghcr.io/linuxserver/librespeed
  pullPolicy: IfNotPresent
  tag: 5.2.4@sha256:6a8a801f5531de520ff07fa123cabbb7a39c4bba05a093be4832cd85e18e2489

envTpl:
  DB_TYPE: "postgresql"
  DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
  DB_PORT: "5432"

envValueFrom:
  DB_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  DB_HOSTNAME:
    secretKeyRef:
      name: dbcreds
      key: plainhost

# -- Enable and configure postgresql database subchart under this key.
# @default -- Enabled (see values.yaml for more details)
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlDatabase: librespeed
  postgresqlUsername: librespeed
  persistence:
    db:
        storageClass: "SCALE-ZFS"
    dbbackups:
      storageClass: "SCALE-ZFS"


##
# Most other defaults are set in questions.yaml
# For other options please refer to the wiki, default_values.yaml or the common library chart
##
