##
# This file contains Values.yaml content that gets added to the output of questions.yaml
# It's ONLY meant for content that the user is NOT expected to change.
# Example: Everything under "image" is not included in questions.yaml but is included here.
##

image:
  repository: miniflux/miniflux
  pullPolicy: IfNotPresent
  tag: 2.0.33@sha256:fb6f88fd9e41cf6feefaaa11e41a23c6e5dca4a9f6c35fadd34d02d9ca249a9d


envValueFrom:
  # -- Postgresql connection parameters. See [lib/pq](https://pkg.go.dev/github.com/lib/pq#hdr-Connection_String_Parameters) for more details.
  DATABASE_URL:
    secretKeyRef:
      name: dbcreds
      key: urlnossl

# -- Configures the probes for the main Pod.
# @default -- See values.yaml
probes:
  liveness:
    enabled: true
    custom: true
    spec:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      httpGet:
        path: /healthcheck
        port: 8080

# -- Enable and configure postgresql database subchart under this key.
# @default -- Enabled (see values.yaml for more details)
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlDatabase: miniflux
  postgresqlUsername: miniflux
  persistence:
    db:
        storageClass: "SCALE-ZFS"
    dbbackups:
      storageClass: "SCALE-ZFS"


##
# Most other defaults are set in questions.yaml
# For other options please refer to the wiki, default_values.yaml or the common library chart
##
