##
# This file contains Values.yaml content that gets added to the output of questions.yaml
# It's ONLY meant for content that the user is NOT expected to change.
# Example: Everything under "image" is not included in questions.yaml but is included here.
##

image:
  repository: sismics/docs
  pullPolicy: IfNotPresent
  tag: v1.9@sha256:bd52127b6509da4b07d7bbc48c7cc82dcbdc59ceab28d9239c591d0d0732f7af

envTpl:
  DATABASE_USER: "{{ .Values.postgresql.postgresqlUsername }}"

envValueFrom:
  DATABASE_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  DATABASE_URL:
    secretKeyRef:
      name: dbcreds
      key: jdbc

# -- Enable and configure postgresql database subchart under this key.
# @default -- See values.yaml
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: teedyuser
  postgresqlDatabase: teedydb
  persistence:
    db:
      storageClass: "SCALE-ZFS"
    dbbackups:
      storageClass: "SCALE-ZFS"

##
# Most other defaults are set in questions.yaml
# For other options please refer to the wiki, default_values.yaml or the common library chart
##
