apiVersion: v2
appVersion: "1.9027.0"
description: Tiny Tiny RSS is a free and open source web-based news feed (RSS/Atom) reader and aggregator
name: tt-rss
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
- tt-rss
home: https://github.com/truecharts/apps/tree/master/charts/stable/tt-rss
icon: https://git.tt-rss.org/fox/tt-rss/raw/branch/master/images/favicon-72px.png
sources:
- https://git.tt-rss.org/fox/tt-rss
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.3.9
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 3.0.16
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
